// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';

// Carga las variables del .env
dotenv.config();

export default defineConfig({
  schema: './prisma/schema.prisma',
  datasource: {
    
    url: process.env.DATABASE_URL,
  },
});