// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from '@prisma/config';
import * as dotenv from 'dotenv';

// Carga las variables del .env explícitamente
dotenv.config();



export default defineConfig({
  schema: './prisma/schema.prisma',
  datasource: {
    // Tu URL original, sin los corchetes y con el puerto 5432 que tenías
    url: "postgresql://postgres:Delfinaluna45nicolas@db.gilrtggvmlzaztgrucjg.supabase.co:5432/postgres",
  },
});